"""remove date_of_birth from patients

Revision ID: 1bce5cf95d90
Revises: 5fd11018b80b
Create Date: 2026-06-23 15:39:47.145124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bce5cf95d90'
down_revision = '5fd11018b80b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discharges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discharge_type', sa.String(length=20), nullable=True))

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.alter_column('next_of_kin_contact_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('next_of_kin_relationship',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.drop_column('date_of_birth')

    with op.batch_alter_table('wards', schema=None) as batch_op:
        batch_op.alter_column('is_permanent_residence',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wards', schema=None) as batch_op:
        batch_op.alter_column('is_permanent_residence',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_of_birth', sa.DATE(), nullable=False))
        batch_op.alter_column('next_of_kin_relationship',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('next_of_kin_contact_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    with op.batch_alter_table('discharges', schema=None) as batch_op:
        batch_op.drop_column('discharge_type')

    # ### end Alembic commands ###
