"""Add comprehensive patient fields for mental health hospital

Revision ID: 5892c0e1b2cd
Revises: 0f4502ee79ef
Create Date: 2026-05-07 10:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5892c0e1b2cd'
down_revision = '0f4502ee79ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hospital_id', sa.String(length=6), nullable=True))
        batch_op.add_column(sa.Column('surname', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('first_names', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('date_of_birth', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('sex', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('race', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('marital_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('occupation', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('religion', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('residential_address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('contact_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('employer_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('employer_address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('next_of_kin_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('next_of_kin_address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('next_of_kin_relationship', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('chief', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('village', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('tribe', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('admission_datetime', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('referring_doctor_hospital', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('diagnosis', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('doctor_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('consultant_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('pharmacy_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('discharge_datetime', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('discharge_datetime')
        batch_op.drop_column('pharmacy_name')
        batch_op.drop_column('consultant_name')
        batch_op.drop_column('doctor_name')
        batch_op.drop_column('diagnosis')
        batch_op.drop_column('referring_doctor_hospital')
        batch_op.drop_column('admission_datetime')
        batch_op.drop_column('tribe')
        batch_op.drop_column('village')
        batch_op.drop_column('chief')
        batch_op.drop_column('next_of_kin_relationship')
        batch_op.drop_column('next_of_kin_address')
        batch_op.drop_column('next_of_kin_name')
        batch_op.drop_column('employer_address')
        batch_op.drop_column('employer_name')
        batch_op.drop_column('contact_number')
        batch_op.drop_column('residential_address')
        batch_op.drop_column('religion')
        batch_op.drop_column('occupation')
        batch_op.drop_column('marital_status')
        batch_op.drop_column('race')
        batch_op.drop_column('sex')
        batch_op.drop_column('date_of_birth')
        batch_op.drop_column('first_names')
        batch_op.drop_column('surname')
        batch_op.drop_column('hospital_id')
    # ### end Alembic commands ###
