"""add is_permanent_residence to ward

Revision ID: 5fd11018b80b
Revises: a87f325a8025
Create Date: 2026-06-18 19:01:59.992652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fd11018b80b'
down_revision = 'a87f325a8025'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_permanent_residence', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wards', schema=None) as batch_op:
        batch_op.drop_column('is_permanent_residence')

    # ### end Alembic commands ###
