"""Add mental health fields

Revision ID: a87f325a8025
Revises: 6c8e2f3a4b91
Create Date: 2026-05-08 05:35:00.592164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a87f325a8025'
down_revision = '6c8e2f3a4b91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.VARCHAR(length=6),
               nullable=False)
        batch_op.alter_column('surname',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('first_names',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('date_of_birth',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('sex',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('race',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('marital_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('occupation',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('residential_address',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('contact_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('next_of_kin_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('next_of_kin_address',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('next_of_kin_relationship',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('admission_datetime',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('referring_doctor_hospital',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('diagnosis',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('doctor_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('consultant_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('pharmacy_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.create_unique_constraint('uq_patient_hospital_id', ['hospital_id'])
        batch_op.drop_column('national_id')
        batch_op.drop_column('gender')
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('gender', sa.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('national_id', sa.VARCHAR(length=50), nullable=False))
        batch_op.drop_constraint('uq_patient_hospital_id', type_='unique')
        batch_op.alter_column('pharmacy_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('consultant_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('doctor_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('diagnosis',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('referring_doctor_hospital',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
        batch_op.alter_column('admission_datetime',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('next_of_kin_relationship',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('next_of_kin_address',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('next_of_kin_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('contact_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('residential_address',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('occupation',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('marital_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('race',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('sex',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('date_of_birth',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('first_names',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('surname',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('hospital_id',
               existing_type=sa.VARCHAR(length=6),
               nullable=True)

    # ### end Alembic commands ###
